exports.messageList = {
  M001: "OTP sent successfully!",
  M002: "User not found!",
  M003: "Invalid OTP!",
  M004: "OTP not found or expired!",
  M005: "OTP expired!",
  M006: "OTP verified successfully!",
  M007: "missing mobileNo or refresh token!",
  M008: "invalid refresh token! Please login again to generate a new token and try again.",
  M009: "admin registered successfully!",
  M010: "refresh token sent successfully!",
  M011: "logged out successfully!",
  M012: "user already exists!",
  M013: "user profile fetched successfully!",
  M014: "user profile updated successfully!",
  M015: "permission denied!",
  M016: "transacion request created successfully!",
  M017: "transaction list fetched successfully!",
  M018: "transaction approved successfully!",
  M019: "transaction rejected successfully!",
  M020: "Referral code is required!",
  M021: "Referral code not found!",
  M022: "Referral code already used!",
  M023: "Referral code applied successfully!",
  M024: "Referral code not applied!",
  M025: "User dashboard data fetched successfully!",
  M026: "Please provide at least one social media link!",
  M027: "Social media links updated successfully!",
  M028: "referral amount percentage updated successfully!",
  M029: "Social Media Links fetched successfully!",
  M030: "Referral amount percentage fetched successfully!",
  M031: "Notification sent successfully!",
  M032: "Notification deleted successfully!",
  M033: "Notification list fetched successfully!",
  M034: "Battle created successfully!",
  M035: "Battle list fetched successfully!",
  M036: "Already playing a battle!",
  M037: "Room details entered successfully!",
  M038: "Battle accepted successfully!",
  M039: "Battle rejected successfully!",
  M040: "Battle details fetched successfully!",
  M041: "Battle details not found!",
  M042: "Battle details updated successfully!",
  M043: "Insufficient balance!",
  M044: "Battle deleted successfully!",
  M045: "Transaction not found!",
  M046: "Referral code invalid!",
  M047: "Battle Status updated successfully!",
  M048: "Battle Status already updated!",
  M049: "User KYC approved successfully!",
  M050: "Payment settings updated successfully!",
  M051: "Admin upi accounts details fetched successfully!",
  M052: "Battle not accepted!",
  M053: "Logined successfully!",
  M054: "Invalid credentials!",
  M055: "Battle create not allowed!",
  M056: "Minimum amount should be 50!",
  M057: "Reffer and earn page details fetched successfully!",
  M058: "Users list fetched successfully!",
  M059: "KYC request users fetched successfully!",
  M060: "Dashboard data fetched successfully!",
  M061: "User blocked successfully!",
  M062: "Penalty applied successfully!",
  M063: "Invalid amount!",
  M064: "User unblocked successfully!",
  M065: "User blocked! Contact admin for more details!",
  M066: "Bonus applied successfully!",
  M067: "Battle Earning Percentage updated successfully!",
  M068: "User details fetched successfully!",
  M069: "KYC rejected successfully!",
  M070: "Invalid request!",
  M071: "One withdraw request already exists!",
  M072: "Withdraw request not alowed, while battle is in progress!",
  M073: "Room No. should be 8 characters long!",
  M074: "Battle accepted by another user!",
};
